app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('frontend.home.index');
});

Route::get('home', function () {
    return redirect('/');
});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

// Account activation
Route::get('auth/activate/{token}', 'Auth\AuthController@getActivate');

Route::group(['namespace' => 'Frontend'], function($router){
    Route::resource('posts', 'PostController');
});

Route::group(['namespace' => 'Frontend', 'prefix' => '', 'middleware' => ''], function($router){
    $router->resource('users', 'UserController');
});

// BACKEND ROUTES
Route::group(['namespace' => 'My', 'prefix' => 'my', 'middleware' => 'auth'], function(\Illuminate\Routing\Router $router){
    $router->get('profile', ['uses' => 'ProfileController@edit', 'as' => 'my.profile']);
    $router->put('profile', ['uses' => 'ProfileController@update', 'as' => 'my.profile']);

    $router->get('account', ['uses' => 'AccountController@edit', 'as' => 'my.account']);
    $router->put('account', ['uses' => 'AccountController@update', 'as' => 'my.account']);

    $router->get('email', ['uses' => 'EmailController@edit', 'as' => 'my.email']);
    $router->put('email', ['uses' => 'EmailController@update', 'as' => 'my.email']);

    $router->get('log', ['uses' => 'LogController@edit', 'as' => 'my.log']);
    $router->put('log', ['uses' => 'LogController@update', 'as' => 'my.log']);
});

// ADMIN ROUTES
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function($router){
    $router->resource('home', 'HomeController');
    $router->resource('reports', 'ReportController');
    $router->resource('users', 'UserController');
    $router->resource('settings', 'SettingController');
});

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Bican\Roles\Traits\HasRoleAndPermission;
use Bican\Roles\Contracts\HasRoleAndPermission as HasRoleAndPermissionContract;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract, HasRoleAndPermissionContract
{
    use Authenticatable, CanResetPassword, HasRoleAndPermission, SoftDeletes;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password', 'status'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    protected function getRolesAsTextAttribute()
    {
        return $this->roles()->get()->implode('name', ', ');
    }

    protected function getPermalinkAttribute()
    {
        return route('users.show', $this->id);
    }

    protected function getRegisteredDateAttribute()
    {
        return $this->created_at->formatLocalized('%e %b %y');
    }

    protected function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\User\StoreRequest;
use App\Repositories\RoleRepository;
use App\Repositories\UserRepository;
use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;

class UserController extends AdminController
{
    /**
     * @var UserRepository
     */
    private $user;
    /**
     * @var RoleRepository
     */
    private $role;

    /**
     * UserController constructor.
     * @param UserRepository $user
     * @param RoleRepository $role
     */
    public function __construct(UserRepository $user, RoleRepository $role)
    {
        $this->user = $user;
        $this->role = $role;
    }


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = $this->user->paginate();
        $totalUsers = $this->user->count();
        return view('admin.users.index', compact('users', 'totalUsers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $roles = $this->role->lists('name', 'id');
        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRequest|Request $request
     * @return Response
     */
    public function store(StoreRequest $request)
    {
        $user = $this->user->createWithRoles($request->only('name', 'email', 'password', 'status'), $request->get('roles', []));

        if($user) {
            flash()->success(trans('users.registration.success', ['name' => $user['name']]));

            if($request->has('continue')) {
                return redirect()->back();
            }

            return redirect()->route('admin.users.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Response
     * @internal param int $id
     */
    public function edit(User $user)
    {
        $roles = $this->role->lists('name', 'id');
        return view('admin.users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreRequest|Request $request
     * @param $user
     * @return Response
     * @internal param int $id
     */
    public function update(StoreRequest $request, $user)
    {
        $user = $this->user->updateWithRoles($user, $request->only('name', 'email', 'status'), $request->get('roles', []));

        if ($user) {
            flash()->success(trans('flash.updated', ['name' => $user['name']]));
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($user)
    {
        $this->user->delete($user->id);

        flash()->success(trans('flash.deleted'));
        return redirect()->route('admin.users.index');
    }
}

app/Http/Controllers/Frontend/UserController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.main')

@section('sidemenu')
    @include('admin.users.menu')
@endsection

@section('content')
    <div class="ui segments">
        <h4 class="ui segment block header">@lang('users.action.add')</h4>

        <div class="ui segment padded">
            <form action="{{ route('admin.users.store') }}" method="POST" class="ui form">
                {{ csrf_field() }}

                <div class="field">
                    <label>@lang('users.name')</label>
                    <input type="text" name="name" value="{{ old('name') }}">
                </div>
                <div class="field">
                    <label>@lang('users.email')</label>
                    <input type="text" name="email" value="{{ old('email') }}">
                </div>
                <div class="field">
                    <label>@lang('users.password')</label>
                    <input type="text" name="password" value="{{ old('password') }}">
                </div>
                <div class="field">
                    <label for="fruit">@lang('users.roles')</label>

                    <div class="inline fields">
                        @foreach($roles as $key=>$value)
                            <div class="field">
                                <div class="ui checkbox">
                                    <input type="checkbox" name="roles[]" value="{{ $key }}" tabindex="0" {{ (old('role') == $key)?"checked=checked":"" }}>
                                    <label>{{ $value }}</label>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="field">
                    <label>@lang('users.status')</label>
                    {!! Form::select('status', \App\Enum\UserStatus::values(), old('status'), ['class' => 'ui dropdown']) !!}
                </div>
                <div class="inline field">
                    <div class="ui checkbox">
                        <input type="checkbox" tabindex="0">
                        <label>@lang('users.registration.send_email')</label>
                    </div>
                </div>

                <div class="ui divider hidden"></div>
                <button class="ui button" type="submit" name="submit" value="1">@lang('form.save')</button>
                <button class="ui button" type="submit" name="continue" value="1">@lang('form.save_continue')</button>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.main')

@section('topmenu')
    <div class="ui breadcrumb" id="breadcrumb">
        <a class="section">Admin</a>
        <div class="divider"> / </div>
        <a class="section" href="{{ route('admin.users.index') }}">Pengguna</a>
        <div class="divider"> / </div>
        <div class="active section">Root</div>
    </div>
@endsection
@section('sidemenu')

    <div class="ui card">
        <div class="content">
            <img class="right floated mini ui image" src="https://s3.amazonaws.com/uifaces/faces/twitter/teleject/24.jpg">
            <div class="header">
                Elliot Fu
            </div>
            <div class="meta">
                @lang('user.registered_since', ['date' => $user['registered_date']])
            </div>
            <div class="description">
                {{ $user['about'] }}
            </div>
        </div>
        <div class="extra content">
            <a href="{{ $user->permalink }}" class="ui button fluid">Public Profile <i class="icon external right"></i></a>
        </div>
    </div>

    <div class="ui red segment">
        <h3 class="ui header red">@lang('users.delete')</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi aperiam aspernatur beatae consectetur ducimus ea earum eos maiores modi, non pariatur possimus quibusdam quisquam reprehenderit, sed suscipit ut voluptas.</p>

        <form action="{{ route('admin.users.destroy', $user['id']) }}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="DELETE">
            <button class="ui button red" type="submit">@lang('action.delete')</button>
        </form>
    </div>

@endsection

@section('content')

    <div class="ui top attached small menu">
        <a class="item active" data-tab="profile">Profil</a>
        <a class="item" data-tab="account">Akun</a>
        <a class="item" data-tab="email">Email</a>
        <a class="item" data-tab="log">Log</a>
    </div>
    <div class="ui bottom attached tab segment active padded" data-tab="first">
        {!! Form::open([
            'method' => 'put',
            'route' => ['admin.users.update', $user['id']],
            'class' => 'ui form'
        ]) !!}

        <div class="field">
            <label>@lang('user.name')</label>
            {!! Form::text('name', old('name', $user['name'])) !!}
        </div>
        <div class="field">
            <label>@lang('user.email')</label>
            {!! Form::text('email', old('email', $user['email'])) !!}
        </div>
        <div class="field">
            <label for="fruit">@lang('user.roles')</label>

            <div class="inline fields">
                @foreach($roles as $key=>$value)
                    <div class="field">
                        <div class="ui checkbox">
                            @if(old("roles[{$key}]", $user->hasRole($key)))
                                {!! Form::checkbox("roles[{$key}]", $key, true) !!}
                            @else
                                {!! Form::checkbox("roles[{$key}]", $key) !!}
                            @endif
                            <label>{{ $value }}</label>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="field">
            <label>@lang('user.status')</label>
            {!! Form::select('status', \App\Enum\UserStatus::values(), old('status', $user['status']), ['class' => 'ui dropdown']) !!}
        </div>

        <div class="ui divider hidden"></div>
        <button class="ui button" type="submit" name="submit" value="1">@lang('action.save')</button>
        <a href="{{ route('admin.users.index') }}" class="ui button basic">@lang('action.cancel')</a>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.main')

@section('topmenu')
    <div class="ui breadcrumb" id="breadcrumb">
        <a class="section">Admin</a>
        <div class="divider"> / </div>
        <div class="active section">Pengguna</div>
    </div>
@endsection


@section('sidemenu')
    @include('admin.users.menu')
@endsection

@section('content')
    <div class="ui top attached menu">
        <div class="menu">
            <div class="item borderless">
                <h4>@lang('entities.user')</h4>
            </div>
        </div>
        <div class="right menu">
            {{--<div class="ui dropdown item">--}}
                {{--<div class="text">Semua Status</div> <i class="dropdown icon"></i>--}}
                {{--<div class="menu">--}}
                    {{--<a href="" class="item">Semua (90)</a>--}}
                    {{--@foreach(\App\Enum\UserStatus::values() as $key=>$value)--}}
                        {{--<a href="" class="item">{{ $value }}</a>--}}
                    {{--@endforeach--}}
                {{--</div>--}}
            {{--</div>--}}
            {{--<div class="ui dropdown item">--}}
                {{--Semua Role <i class="dropdown icon"></i>--}}
                {{--<div class="menu">--}}
                    {{--<a href="" class="item">Semua (90)</a>--}}
                    {{--@foreach(\App\Enum\UserStatus::values() as $key=>$value)--}}
                        {{--<a href="" class="item">{{ $value }}</a>--}}
                    {{--@endforeach--}}
                {{--</div>--}}
            {{--</div>--}}
            <div class="ui right aligned item">
                <div class="ui transparent icon input">
                    <input class="prompt" type="text" placeholder="@lang('action.search')">
                    <i class="search link icon"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="ui segment attached fitted">
        <table class="ui very compact table bottom small">
            <thead>
            <tr>
                <th>@lang('user.name')/@lang('user.email')</th>
                <th>@lang('user.roles')</th>
                <th>@lang('user.status')</th>
                <th>@lang('user.registered')</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>
                        <h4>{{ $user['name'] }}</h4>
                        {{ $user['email'] }}
                    </td>
                    <td>{{ $user['roles_as_text'] }}</td>
                    <td>{{ $user['status'] }}</td>
                    <td>{{ $user['registered_date'] }}</td>
                    <td class="right aligned"><a href="{{ route('admin.users.edit', $user['id']) }}" class="ui button basic mini">@lang('action.manage')</a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <div class="ui menu bottom attached">
        <div class="item borderless">
            <small>{!! with(new \Laravolt\Support\Pagination\SemanticUiPagination($users))->summary() !!}</small>
        </div>
        {!! with(new \Laravolt\Support\Pagination\SemanticUiPagination($users))->render('attached bottom right') !!}
    </div>

@endsection

resources/views/admin/users/menu.blade.php
<div class="ui menu vertical fluid">
    <div class="item">
        <a href="{{ route('admin.users.create') }}" class="ui button fluid green">@lang('action.add')</a>
    </div>
    <div class="item">
        <h3 class="header">Menu Terkait</h3>
        <div class="menu">
            <a href="" class="item">Permission</a>
            <a href="" class="item">Role</a>
        </div>
    </div>
</div>